version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: cursos_online_db
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: cursos_online
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: